### ISSUE TITLE
Failure to update interscript-js repo on gem release

### ISSUE THREAD

**Issue by webdev778** [interscript/interscript#683]
Automatically, update interscript-js repo with new systems on gem release

Currently, it's not updating interscript-js repo
![image](https://user-images.githubusercontent.com/28761746/102311219-cdd44780-3faf-11eb-9696-77ec6ea15510.png)

I'd like to take your attention to here, @camobap.

One thing to consider, they have different version.
### Interscript GEM
![image](https://user-images.githubusercontent.com/28761746/102311377-1d1a7800-3fb0-11eb-823b-d9ec2b029164.png)

### Interscript JS
![image](https://user-images.githubusercontent.com/28761746/102311467-4c30e980-3fb0-11eb-89a4-7c1351ff21eb.png)

_Originally posted by @webdev778 in https://github.com/interscript/interscript/issues/682#issuecomment-745775915_

**Comment by ronaldtse** [comment]
@webdev778 is this still relevant? Thanks.

**Comment by webdev778** [comment]
@ronaldtse, good catch. not any more relevant. closed
