### ISSUE TITLE
Question to @bilashsaha

### ISSUE THREAD

**Issue by webdev778** [interscript/interscript#692]
there are a lot of maps written like this
`    - pattern: ([ක]=?)(?=[\u0dcf\u0dd0\u0dd1\u0dd2\u0dd3\u0dd4\u0dd6\u0dd8\u0df2\u0dd9\u0dda\u0ddb\u0ddc\u0ddd\u0dde\u0dca])
      result: 'k'`

of course, it works.
`([ක]=?)(?=[\u0dcf\u0dd0\u0dd1\u0dd2\u0dd3\u0dd4\u0dd6\u0dd8\u0df2\u0dd9\u0dda\u0ddb\u0ddc\u0ddd\u0dde\u0dca])`
this syntax can be simplified to 
`ක(?=[\u0dcf\u0dd0\u0dd1\u0dd2\u0dd3\u0dd4\u0dd6\u0dd8\u0df2\u0dd9\u0dda\u0ddb\u0ddc\u0ddd\u0dde\u0dca])`

I just wonder if it was your intention, but I'm 100% sure it wasn't though.
I'd appreciate your clarification.

ping @bilashsaha

**Comment by ronaldtse** [comment]
@bilashsaha just wondering if the rule can be simplified as proposed. Thanks!

**Comment by bilashsaha** [comment]
@webdev778 You are right. I did not have a second look at these codes. I will take care of these.
